version: '3.8'
services:
 mysql:
  image: mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
   MYSQL_USER_FILE: /run/secrets/MYSQL_USER
   MYSQL_DATABASE_FILE: /run/secrets/MYSQL_DATABASE
  command: --default-authentication-plugin=mysql_native_password
  ports:
   - 3306:3306
  deploy:
   replicas: 1
  secrets:
   - MYSQL_ROOT_PASSWORD
   - MYSQL_USER
   - MYSQL_DATABASE

 adminer:
  image: adminer
  restart: always
  ports:
   - 8080:8080
secrets:
 MYSQL_ROOT_PASSWORD:
  external: true
 MYSQL_USER:
  external: true
 MYSQL_DATABASE:
  external: true
