version: '3.8'

services:
 db:
  image: mysql:5
  environment:
   MYSQL_ROOT_PASSWORD: venkat
  ports:
   - 3306:3306
  container_name: mydb

 adminer:
  image: adminer
  links:
   - db
  ports:
   - 8080:8080
  container_name: myadminer

networks:
 default:
  external:
   name: venkat
